version: '3.3'
services:
  collact-api-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:8080'
    environment:
      - API_SERVER_PORT=8080
      - DB_HOST=collact-db
      - DB_PORT=5432
      - DB_USER=collact
      - DB_PASSWORD=collact_password
      - DB_NAME=collact

    command: wait-for-it collact-db:5432 -- npm run start
    depends_on:
      - collact-db

  collact-db:
    image: postgres:13.1-alpine
    environment:
      - POSTGRES_USER=collact
      - POSTGRES_PASSWORD=collact_password
      - POSTGRES_DB=collact
