version: '3.3'
services:
  collact-api:
    container_name: collact-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '80:8080'
    environment:
      - API_SERVER_PORT=8080
      - TYPEORM_DB_HOST=collact-db
      - TYPEORM_DB_PORT=5432
      - TYPEORM_DB_USER=collact
      - TYPEORM_DB_PASSWORD=collact_password
      - TYPEORM_DB_NAME=collact
      - JWT_SECRET=""
      - AWS_S3_BUCKET="collact-dev"
      - AWS_REGION="ap-northeast-2"
      - AWS_ACCESS_KEY_ID=""
      - AWS_SECRET_ACCESS_KEY=""
    command: /collact/www/.docker/entrypoint.sh
    depends_on:
      - collact-db

  collact-db:
    container_name: collact-db
    image: postgres:13.1-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=collact
      - POSTGRES_PASSWORD=collact_password
      - POSTGRES_DB=collact
